# mysql连接
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.69.44:3306/second_kill?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root
#redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 50
        max-idle: 20
# mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml
  type-aliases-package: com.ms.consumer.dao
server:
  port: 8999


